### ISSUE TITLE
Backend support

### ISSUE THREAD

**Issue by ehsanmok** [nhynes/tvm-rs#4]
In your place, do you also want to support TVM backend as you've added its C API in the build? I think, we should wait and see TVM matures first!

**Comment by nhynes** [comment]
By backend, do you mean like CUDA/OpenGL/...? I think that CPU-only is fine for now, but adding support for the various runtimes would be nice in the future. The main draw of a Rust runtime is the thread+memory safety, which is mostly relevant for CPU.

**Comment by ehsanmok** [comment]
Well, I meant since you've included `c_backend_api.h` maybe it was too soon to for that but I get your intentions now :)
