### ISSUE TITLE
Relation to Ekiden

### ISSUE THREAD

**Issue by roehst** [nhynes/tvm-rs#5]
@nhynes Hi Nicholas, is this project in anyway related to the "Ekiden" blockchain project described here which cites you as author?

https://arxiv.org/abs/1804.05141

**Comment by nhynes** [comment]
Having a Rust runtime for TVM is a good thing, in general :)

https://discuss.tvm.ai/t/rust-frontend-support/211

**Comment by roehst** [comment]
@nhynes can we chat a bit about how this project integrates with Ekiden?

**Comment by nhynes** [comment]
Well, that's the thing: it doesn't. I actually started this library because it was too easy to corrupt the heap when setting a DLTensor pointer incorrectly. To my knowledge, this library doesn't integrate with Ekiden, but maybe with a bit of effort it could be used in a similar environment.
